"""Add notifications and uploads

Revision ID: 272f2667924a
Revises: 0001_initial
Create Date: 2026-09-24 19:09:58.329884
"""
from alembic import op
import sqlalchemy as sa


revision = '272f2667924a'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('donations_tracking_id_key', 'donations', type_='unique')
    op.drop_index('ix_donations_tracking_id', table_name='donations')
    op.create_index(op.f('ix_donations_tracking_id'), 'donations', ['tracking_id'], unique=True)
    op.drop_constraint('organizations_slug_key', 'organizations', type_='unique')
    op.drop_index('ix_organizations_slug', table_name='organizations')
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.create_index('ix_organizations_slug', 'organizations', ['slug'], unique=False)
    op.create_unique_constraint('organizations_slug_key', 'organizations', ['slug'])
    op.drop_index(op.f('ix_donations_tracking_id'), table_name='donations')
    op.create_index('ix_donations_tracking_id', 'donations', ['tracking_id'], unique=False)
    op.create_unique_constraint('donations_tracking_id_key', 'donations', ['tracking_id'])
    # ### end Alembic commands ###
